services:
  db:
    image: timescale/timescaledb:2.25.2-pg18
    container_name: timescale_db_control_system
    command: ["postgres", "-p", "${POSTGRES_PORT}", "-c", "synchronous_commit=off"]
    env_file:
      - .env
    volumes:
      - timescale_db_data:/var/lib/postgresql/data
    networks:
      - control-system-network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: control_system_api
    command: bash ./scripts/app-start.sh
    networks:
      - control-system-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
      - redis
      - rabbitmq

  worker:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: control_system_worker
    command: bash ./scripts/worker-start.sh
    networks:
      - control-system-network
    depends_on:
      - db
      - rabbitmq

  celery-worker:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: control_system_celery_worker
    command: bash ./scripts/celery-worker-start.sh
    networks:
      - control-system-network
    depends_on:
      - db
      - rabbitmq

  redis:
    image: redis:8.2
    container_name: redis_control_system
    networks:
      - control-system-network
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq_control_system
    command: sh -c "rabbitmq-plugins enable rabbitmq_auth_mechanism_ssl && rabbitmq-server"
    networks:
      - control-system-network
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_EXTERNAL_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infra/rabbitmq/certs:/etc/rabbitmq/certs:ro
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_control_system
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - control-system-network
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  timescale_db_data:
    name: timescale_db_data
    external: true
  redis_data:
    name: redis_data
    external: true
  rabbitmq_data:
    name: rabbitmq_data
    external: true

networks:
  control-system-network:
    external: true
