from app.core.exc.base.exceptions import (
    ObjectNotFoundException,
    ObjectAlreadyExistsException,
    GoneException,
    NotAuthorizedException,
    ForbiddenException,
    BadRequestException,
)
from app.core.exc.auth.exceptions import (
    UserAlreadyExistsException,
    VerificationCodeAlreadySentException,
    VerificationFailedOrExpiredException,
    TokenRefreshException,
    UserNotFoundException,
    InvalidCredentialsException,
    UserDeactivatedException,
    PasswordInvalidException,
    ForgotPasswordCodeAlreadySentException,
    ForgotPasswordCodeFailedOrExpiredException,
)
from app.core.exc.tenant import (
    TenantIdRequiredException,
    InvalidTenantIdFormatException,
    TenantAccessDeniedException,
)
from app.core.exc.organization import (
    OrganizationAccessDeniedException,
    OrganizationPermissionDeniedException,
    CannotRemoveOwnerException,
    AdminCanOnlyRemoveMembersException,
    OwnerCannotLeaveException,
    CannotChangeOwnRoleException,
    RoleAlreadyAssignedException,
)

__all__ = [
    "ObjectNotFoundException",
    "ObjectAlreadyExistsException",
    "GoneException",
    "NotAuthorizedException",
    "ForbiddenException",
    "BadRequestException",
    "UserAlreadyExistsException",
    "VerificationCodeAlreadySentException",
    "VerificationFailedOrExpiredException",
    "TokenRefreshException",
    "UserNotFoundException",
    "InvalidCredentialsException",
    "UserDeactivatedException",
    "PasswordInvalidException",
    "ForgotPasswordCodeAlreadySentException",
    "ForgotPasswordCodeFailedOrExpiredException",
    "TenantIdRequiredException",
    "InvalidTenantIdFormatException",
    "TenantAccessDeniedException",
    "OrganizationAccessDeniedException",
    "OrganizationPermissionDeniedException",
    "CannotRemoveOwnerException",
    "AdminCanOnlyRemoveMembersException",
    "OwnerCannotLeaveException",
    "CannotChangeOwnRoleException",
    "RoleAlreadyAssignedException",
]
