# Allow standard connections on 5672 (for Worker/FastAPI in Docker network)
listeners.tcp.default = 5672

# Enable mTLS on port 5671 (for Edge Collectors)
listeners.ssl.default = 5671

# Path to infrastructure certificates (Inside the container)
ssl_options.cacertfile = /etc/rabbitmq/certs/ca_certificate.pem
ssl_options.certfile   = /etc/rabbitmq/certs/server_certificate.pem
ssl_options.keyfile    = /etc/rabbitmq/certs/server_key.pem

# HARD SECURITY: Require peer certificate
ssl_options.verify     = verify_peer
ssl_options.fail_if_no_peer_cert = true

# AUTHORIZATION PLUGINS
auth_mechanisms.1 = PLAIN
auth_mechanisms.2 = EXTERNAL

# Instruct RabbitMQ to use the Common Name (our UUID) as the internal username
ssl_cert_login_from = common_name
